Repository Evarisk/DoliSecu, pull requests merged in 2025-05, with the labels that each got.

#12 #2 [Conf] fix: check if user is on windows server
  dolisecuindex.php
  langs/fr_FR/dolisecu.lang
Labels: 0, Enhancement

#10 #9 [Mod] add: clean codes files
  .editorconfig
  .github/workflows/changelog.yml
  README.md
  admin/about.php
  admin/index.php
  admin/setup.php
  changelog.md
  core/index.php
  core/modules/index.php
  core/modules/modDoliSecu.class.php
  css/dolisecu_all.css
  dolisecu.main.inc.php
  img/index.php
  index.php
  langs/fr_FR/dolisecu.lang
  langs/index.php
  lib/dolisecu.lib.php
  lib/index.php
Labels: 5, Enhancement

#14 #13 [Mod] add: version number
  README.md
  core/modules/modDoliSecu.class.php
Labels: 0, Enhancement

#16 #15 [Index] fix: wrong include
  dolisecuindex.php
Labels: 0, Bug
